/**
 *  @file FR_trig_table.h - 129-entry quadrant sine table for FR_Math 2.0
 *
 *  This table covers one quadrant [0, pi/2] inclusive in 128 intervals (so
 *  129 entries). Indexed by a 7-bit BAM (binary angular measure) sub-index.
 *  Used by fr_sin_bam / fr_cos_bam in FR_math.c.
 *
 *  Output format: u0.15 (unsigned, 15 fractional bits). So
 *      gFR_SIN_TAB_Q[0]   = round(sin(0) * 32768)            = 0
 *      gFR_SIN_TAB_Q[64]  = round(sin(pi/4) * 32768)         = 23170
 *      gFR_SIN_TAB_Q[128] = round(sin(pi/2) * 32768)         = 32768
 *
 *  Generated by tools/coef-gen.py — do not hand-edit.
 *
 *  @copy Copyright (C) <2001-2026>  <M. A. Chatterjee>
 *  @author M A Chatterjee <deftio [at] deftio [dot] com>
 *
 *  Same zlib license as the rest of the library.
 */
#ifndef __FR_TRIG_TABLE_H__
#define __FR_TRIG_TABLE_H__

#ifdef __cplusplus
extern "C" {
#endif

#define FR_TRIG_TABLE_BITS  (7)                          /* log2(intervals) */
#define FR_TRIG_TABLE_SIZE  ((1 << FR_TRIG_TABLE_BITS) + 1) /* entries = intervals + 1 */

/* Derived constants for fr_sin_bam / fr_cos_bam.
 *
 * The BAM has 16 bits total: 2 top bits for quadrant, 14 bits in-quadrant.
 * The in-quadrant value is split into (FR_TRIG_TABLE_BITS) table-index bits
 * and (FR_TRIG_FRAC_BITS) interpolation-fraction bits, so
 *     FR_TRIG_TABLE_BITS + FR_TRIG_FRAC_BITS = 14.
 *
 * Changing FR_TRIG_TABLE_BITS (and regenerating the table with coef-gen.py)
 * is the single knob for ROM-vs-precision trade-off. Every other constant
 * below derives from it automatically.
 */
#define FR_TRIG_FRAC_BITS   (14 - FR_TRIG_TABLE_BITS)
#define FR_TRIG_FRAC_MAX    (1 << FR_TRIG_FRAC_BITS)
#define FR_TRIG_FRAC_MASK   (FR_TRIG_FRAC_MAX - 1)
#define FR_TRIG_FRAC_HALF   (FR_TRIG_FRAC_MAX >> 1)   /* rounding bias */
#define FR_TRIG_QUADRANT    (1 << 14)                 /* in-quadrant span */

static const unsigned short gFR_SIN_TAB_Q[FR_TRIG_TABLE_SIZE] = {
        0,   402,   804,  1206,  1608,  2009,  2411,  2811,
     3212,  3612,  4011,  4410,  4808,  5205,  5602,  5998,
     6393,  6787,  7180,  7571,  7962,  8351,  8740,  9127,
     9512,  9896, 10279, 10660, 11039, 11417, 11793, 12167,
    12540, 12910, 13279, 13646, 14010, 14373, 14733, 15091,
    15447, 15800, 16151, 16500, 16846, 17190, 17531, 17869,
    18205, 18538, 18868, 19195, 19520, 19841, 20160, 20475,
    20788, 21097, 21403, 21706, 22006, 22302, 22595, 22884,
    23170, 23453, 23732, 24008, 24279, 24548, 24812, 25073,
    25330, 25583, 25833, 26078, 26320, 26557, 26791, 27020,
    27246, 27467, 27684, 27897, 28106, 28311, 28511, 28707,
    28899, 29086, 29269, 29448, 29622, 29792, 29957, 30118,
    30274, 30425, 30572, 30715, 30853, 30986, 31114, 31238,
    31357, 31471, 31581, 31686, 31786, 31881, 31972, 32058,
    32138, 32214, 32286, 32352, 32413, 32470, 32522, 32568,
    32610, 32647, 32679, 32706, 32729, 32746, 32758, 32766,
    32768
};

/* ---- Tangent table: 65 entries covering one octant [0, pi/4] ----
 *
 * gFR_TAN_TAB_O[i] = round(tan(i * pi/4 / 64) * 32768)  for i = 0..64
 *
 * Output format: u0.15 stored as u16 (unsigned, 15 fractional bits).
 * Entry[64] = 32768 (tan 45° = 1.0 exactly) requires u16; it does not
 * fit in s16.
 *
 * The table is used by fr_tan_bam() in FR_math.c. The first-octant
 * lookup gives a raw result in u0.15 which is then shifted to s15.16.
 * Second-octant (>45°) uses the reciprocal identity:
 *   tan(pi/2 - x) = 1/tan(x)
 *
 * 130 bytes ROM.
 */
#define FR_TAN_TABLE_BITS  (6)
#define FR_TAN_TABLE_SIZE  ((1 << FR_TAN_TABLE_BITS) + 1)  /* 65 */
#define FR_TAN_FRAC_BITS   (13 - FR_TAN_TABLE_BITS)        /* 7 */
#define FR_TAN_FRAC_MAX    (1 << FR_TAN_FRAC_BITS)         /* 128 */
#define FR_TAN_FRAC_MASK   (FR_TAN_FRAC_MAX - 1)           /* 0x7F */
#define FR_TAN_FRAC_HALF   (FR_TAN_FRAC_MAX >> 1)          /* 64 */
#define FR_TAN_OCTANT      (1 << 13)                        /* 8192 */

static const unsigned short gFR_TAN_TAB_O[FR_TAN_TABLE_SIZE] = {
        0,   402,   804,  1207,  1610,  2013,  2417,  2822,
     3227,  3634,  4042,  4450,  4861,  5272,  5686,  6101,
     6518,  6937,  7358,  7782,  8208,  8637,  9068,  9503,
     9940, 10381, 10825, 11273, 11725, 12180, 12640, 13104,
    13573, 14046, 14525, 15009, 15498, 15993, 16494, 17001,
    17515, 18035, 18563, 19098, 19640, 20191, 20750, 21318,
    21895, 22481, 23078, 23685, 24302, 24931, 25572, 26226,
    26892, 27572, 28266, 28975, 29699, 30440, 31198, 31973,
    32768
};

#ifdef __cplusplus
} // extern "C"
#endif

#endif /* __FR_TRIG_TABLE_H__ */
