/**
 *  @file FR_trig_table.h - 129-entry quadrant cosine table for FR_Math 2.0
 *
 *  This table covers one quadrant [0, pi/2] inclusive in 128 intervals (so
 *  129 entries). Indexed by a 7-bit BAM (binary angular measure) sub-index.
 *  Used by fr_cos_bam / fr_sin_bam in FR_math.c.
 *
 *  Output format: s0.15 (signed, 15 fractional bits). So
 *      gFR_COS_TAB_Q[0]   = round(cos(0) * 32767)        = 32767
 *      gFR_COS_TAB_Q[64]  = round(cos(pi/4) * 32767)     ~ 23170
 *      gFR_COS_TAB_Q[128] = round(cos(pi/2) * 32767)     = 0
 *
 *  Generated by tools/coef-gen.py — do not hand-edit.
 *
 *  @copy Copyright (C) <2001-2026>  <M. A. Chatterjee>
 *  @author M A Chatterjee <deftio [at] deftio [dot] com>
 *
 *  Same zlib license as the rest of the library.
 */
#ifndef __FR_TRIG_TABLE_H__
#define __FR_TRIG_TABLE_H__

#ifdef __cplusplus
extern "C" {
#endif

#define FR_TRIG_TABLE_BITS  (7)                          /* log2(intervals) */
#define FR_TRIG_TABLE_SIZE  ((1 << FR_TRIG_TABLE_BITS) + 1) /* entries = intervals + 1 */

/* Derived constants for fr_cos_bam / fr_sin_bam.
 *
 * The BAM has 16 bits total: 2 top bits for quadrant, 14 bits in-quadrant.
 * The in-quadrant value is split into (FR_TRIG_TABLE_BITS) table-index bits
 * and (FR_TRIG_FRAC_BITS) interpolation-fraction bits, so
 *     FR_TRIG_TABLE_BITS + FR_TRIG_FRAC_BITS = 14.
 *
 * Changing FR_TRIG_TABLE_BITS (and regenerating the table with coef-gen.py)
 * is the single knob for ROM-vs-precision trade-off. Every other constant
 * below derives from it automatically.
 */
#define FR_TRIG_FRAC_BITS   (14 - FR_TRIG_TABLE_BITS)
#define FR_TRIG_FRAC_MAX    (1 << FR_TRIG_FRAC_BITS)
#define FR_TRIG_FRAC_MASK   (FR_TRIG_FRAC_MAX - 1)
#define FR_TRIG_FRAC_HALF   (FR_TRIG_FRAC_MAX >> 1)   /* rounding bias */
#define FR_TRIG_QUADRANT    (1 << 14)                 /* in-quadrant span */

static const short gFR_COS_TAB_Q[FR_TRIG_TABLE_SIZE] = {
    32767, 32765, 32757, 32745, 32728, 32705, 32678, 32646,
    32609, 32567, 32521, 32469, 32412, 32351, 32285, 32213,
    32137, 32057, 31971, 31880, 31785, 31685, 31580, 31470,
    31356, 31237, 31113, 30985, 30852, 30714, 30571, 30424,
    30273, 30117, 29956, 29791, 29621, 29447, 29268, 29085,
    28898, 28706, 28510, 28310, 28105, 27896, 27683, 27466,
    27245, 27019, 26790, 26556, 26319, 26077, 25832, 25582,
    25329, 25072, 24811, 24547, 24279, 24007, 23731, 23452,
    23170, 22884, 22594, 22301, 22005, 21705, 21403, 21096,
    20787, 20475, 20159, 19841, 19519, 19195, 18868, 18537,
    18204, 17869, 17530, 17189, 16846, 16499, 16151, 15800,
    15446, 15090, 14732, 14372, 14010, 13645, 13279, 12910,
    12539, 12167, 11793, 11417, 11039, 10659, 10278,  9896,
     9512,  9126,  8739,  8351,  7962,  7571,  7179,  6786,
     6393,  5998,  5602,  5205,  4808,  4410,  4011,  3612,
     3212,  2811,  2410,  2009,  1608,  1206,   804,   401,
        0
};

/* ---- Tangent table: 65 entries covering one octant [0, pi/4] ----
 *
 * gFR_TAN_TAB_O[i] = round(tan(i * pi/4 / 64) * 32768)  for i = 0..64
 *
 * Output format: u0.15 stored as u16 (unsigned, 15 fractional bits).
 * Entry[64] = 32768 (tan 45° = 1.0 exactly) requires u16; it does not
 * fit in s16.
 *
 * The table is used by fr_tan_bam() in FR_math.c. The first-octant
 * lookup gives a raw result in u0.15 which is then shifted to s15.16.
 * Second-octant (>45°) uses the reciprocal identity:
 *   tan(pi/2 - x) = 1/tan(x)
 *
 * 130 bytes ROM.
 */
#define FR_TAN_TABLE_BITS  (6)
#define FR_TAN_TABLE_SIZE  ((1 << FR_TAN_TABLE_BITS) + 1)  /* 65 */
#define FR_TAN_FRAC_BITS   (13 - FR_TAN_TABLE_BITS)        /* 7 */
#define FR_TAN_FRAC_MAX    (1 << FR_TAN_FRAC_BITS)         /* 128 */
#define FR_TAN_FRAC_MASK   (FR_TAN_FRAC_MAX - 1)           /* 0x7F */
#define FR_TAN_FRAC_HALF   (FR_TAN_FRAC_MAX >> 1)          /* 64 */
#define FR_TAN_OCTANT      (1 << 13)                        /* 8192 */

static const unsigned short gFR_TAN_TAB_O[FR_TAN_TABLE_SIZE] = {
        0,   402,   804,  1207,  1610,  2013,  2417,  2822,
     3227,  3634,  4042,  4450,  4861,  5272,  5686,  6101,
     6518,  6937,  7358,  7782,  8208,  8637,  9068,  9503,
     9940, 10381, 10825, 11273, 11725, 12180, 12640, 13104,
    13573, 14046, 14525, 15009, 15498, 15993, 16494, 17001,
    17515, 18035, 18563, 19098, 19640, 20191, 20750, 21318,
    21895, 22481, 23078, 23685, 24302, 24931, 25572, 26226,
    26892, 27572, 28266, 28975, 29699, 30440, 31198, 31973,
    32768
};

#ifdef __cplusplus
} // extern "C"
#endif

#endif /* __FR_TRIG_TABLE_H__ */
